name: Refresh

on:
  schedule:
    - cron:  '0 * * * *'

env:
  UNSPLASH_ACCESS_KEY: ${{ secrets.UNSPLASH_ACCESS_KEY }}
  UNSPLASH_USERNAMES: ${{ vars.UNSPLASH_USERNAMES }}
  FALLBACK_TARGET: ${{ vars.FALLBACK_TARGET }}

jobs:
  refresh:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 2

      - name: 'Update _redirects'
        run: |
          chmod +x ./refresh.sh
          ./refresh.sh

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_author: Author <actions@github.com>
          commit_message: "Update _redirects"
          commit_options: '--amend --no-edit'
          push_options: '--force'
          skip_fetch: true